### ISSUE TITLE
Extractor doesn't seem to be producing function call information

### ISSUE THREAD

**Issue by atgeller** [rust-corpus/qrates#150]
I'm trying to write a query to get information about how often a particular function is called by various crates. However, after following the steps to extract the data, both `terminators_call.rc` and `terminators_call_const_target.rc` in the database seem to be empty. I noticed when running `query all` that there's a log mention saying "Number of packages from which at least one build was selected: 0", could this be an issue?

I'm running Ubuntu 20.04.2 LTS on WSL2, and cargo 1.57.0-nightly (c7957a74b 2021-10-11) with the latest commit on main.

Thanks!

**Comment by vakaras** [comment]
Thanks for opening an issue. I will try to look into this over the weekend.

**Comment by vakaras** [comment]
Let me know if my changes do not fix the issue.
